"""
Database layer: five tables, on SQLite (my laptop) or Postgres (deployed).

Which one is decided by the DATABASE_URL setting:
  not set                      -> SQLite file (ONTRACK_DB, default ontrack.db)
  postgresql://user:pw@host/db -> Postgres

  settings       key/value pairs (the monthly budget lives here)
  items          things you want to buy ("Smartwatch")
  links          store pages for an item (Amazon AND Fastrack for the watch);
                 an item's price is its cheapest link
  price_history  one row per successful price check, so we can show
                 "↓ ₹40 since you saved it" and the lowest price seen
  status_changes one row per status move (planned → later → planned → purchased),
                 so we can answer "what did I postpone?"

Items and links are separate tables because one thing you want can be sold in
several places. If every link were its own item, the watch would be counted
twice in the budget.
"""

from __future__ import annotations

import os
import sqlite3

SCHEMA = """
CREATE TABLE IF NOT EXISTS settings (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS items (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    name         TEXT    NOT NULL,
    status       TEXT    NOT NULL DEFAULT 'planned',  -- 'planned' | 'later' | 'purchased'
    priority     INTEGER NOT NULL DEFAULT 0,   -- higher = buy first
    manual_price DOUBLE PRECISION,                         -- used only when no link has a price
    note         TEXT,
    purchased_price DOUBLE PRECISION,                      -- what you actually paid
    purchased_at TEXT,                         -- when you actually bought it
    created_at   TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS links (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id      INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    url          TEXT    NOT NULL UNIQUE,      -- cleaned URL, so the same product can't be saved twice
    title        TEXT,
    price        DOUBLE PRECISION,                         -- what you'd pay (latest successful check)
    mrp          DOUBLE PRECISION,                         -- struck-through price, if the store shows one
    image        TEXT,
    method       TEXT,                         -- which extractor strategy worked
    last_checked TEXT,                         -- when we last TRIED (success or not)
    last_error   TEXT,                         -- why the last try failed, NULL if it worked
    created_at   TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS price_history (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    link_id    INTEGER NOT NULL REFERENCES links(id) ON DELETE CASCADE,
    price      DOUBLE PRECISION NOT NULL,
    mrp        DOUBLE PRECISION,
    checked_at TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS status_changes (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id    INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
    from_status TEXT,
    to_status   TEXT   NOT NULL,
    changed_at  TEXT   NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_links_item   ON links(item_id);
CREATE INDEX IF NOT EXISTS idx_history_link ON price_history(link_id, checked_at);
"""


def db_path() -> str:
    return os.getenv("ONTRACK_DB", "ontrack.db")


def database_url() -> str | None:
    """The Postgres address, or None for SQLite."""
    return os.getenv("DATABASE_URL") or None


# Postgres spells "a number that counts up by itself" differently. Everything
# else in SCHEMA already works on both, so we translate this one phrase
# instead of keeping two copies of every table.
# BY DEFAULT (not ALWAYS) lets the copy script keep the ids from ontrack.db.
PG_SCHEMA = SCHEMA.replace("INTEGER PRIMARY KEY AUTOINCREMENT",
                           "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")


def _to_pg(sql: str) -> str:
    """SQLite writes placeholders as ?, Postgres (psycopg) as %s.
    psycopg also treats a lone % as the start of a placeholder, so a real %
    (as in LIKE 'http%') must be written %%. Order matters: double the
    existing % signs first, then turn ? into %s.
    Our SQL never has a ? inside quotes, so a plain replace is safe."""
    return sql.replace("%", "%%").replace("?", "%s")


class PgConnection:
    """A Postgres connection that looks like our SQLite one, so services.py
    doesn't need to know which database it's talking to: same execute(),
    same ? placeholders, rows readable as row["price"], commit(), close()."""

    def __init__(self, url: str):
        import psycopg                       # only needed when Postgres is used
        from psycopg.rows import dict_row
        self.raw = psycopg.connect(url, row_factory=dict_row)

    def execute(self, sql: str, params=()):
        # Always pass a tuple (even an empty one) so psycopg always reads
        # placeholders, and the %% from _to_pg always turns back into %.
        return self.raw.execute(_to_pg(sql), tuple(params))

    def executescript(self, script: str) -> None:
        self.raw.execute(script)             # no params: several statements at once

    def commit(self) -> None:
        self.raw.commit()

    def rollback(self) -> None:
        self.raw.rollback()

    def close(self) -> None:
        self.raw.close()


def connect(path: str | None = None):
    url = database_url()
    if url and path is None:
        return PgConnection(url)
    conn = sqlite3.connect(path or db_path(), check_same_thread=False)
    conn.row_factory = sqlite3.Row          # rows behave like dicts: row["price"]
    conn.execute("PRAGMA foreign_keys = ON")  # SQLite ignores REFERENCES/CASCADE unless this is on
    return conn


def init(conn) -> None:
    conn.executescript(PG_SCHEMA if isinstance(conn, PgConnection) else SCHEMA)
    conn.commit()